# Site settings
title: Jekyll-materialize
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
url: "http://yourdomain.com"
baseurl: ""
logo: jekyll-<b>materialize</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: asqus23@gmail.com
    facebook:
        show: false
        username: ""
    github:
        show: false
        username: ""
    twitter:
        show: false
        username: ""
    disqus:
        show: false
        username: ""
    linkedin:
        show: false
        username: ""
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-feed
