# Site settings
title: combatTB
description: > # Description of project
url: "http://www.combattb.org"
baseurl: "combat-tb"
logo: combat<b>TB</b>
paginate: 3
paginate_path: "/page:num/"
owner:
    email: combattb@gmail.com
    facebook:
        show: false
        username: ""
    github:
        show: false
        username: ""
    twitter:
        show: false
        username: ""
    disqus:
        show: false
        username: ""
    linkedin:
        show: false
        username: ""
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-feed
